import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
const $=id=>document.getElementById(id);const base=$('base'),shoulder=$('shoulder'),elbow=$('elbow'),grip=$('grip'),speed=$('speed');
let saved=[],mode='MANUAL',estopped=false,running=false,cycles=0,held=false,telemetry=[];const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const host=$('robot3d'),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(42,1,.1,100),renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;host.appendChild(renderer.domElement);camera.position.set(7,5.3,8.5);const orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.target.set(0,2.4,0);orbit.minDistance=5;orbit.maxDistance=15;
scene.add(new THREE.HemisphereLight(0xbfe2ff,0x17202c,2.2));const key=new THREE.DirectionalLight(0xffffff,4);key.position.set(5,9,6);key.castShadow=true;scene.add(key);const fill=new THREE.DirectionalLight(0x4b9cff,2);fill.position.set(-5,4,-3);scene.add(fill);scene.add(new THREE.GridHelper(12,24,0x315a82,0x193047));const axes=new THREE.AxesHelper(2.2);axes.position.y=.03;scene.add(axes);
const floor=new THREE.Mesh(new THREE.CircleGeometry(6,64),new THREE.MeshStandardMaterial({color:0x0a1420,roughness:.9}));floor.rotation.x=-Math.PI/2;floor.position.y=-.02;floor.receiveShadow=true;scene.add(floor);const orange=new THREE.MeshStandardMaterial({color:0xff7a00,metalness:.5,roughness:.28}),dark=new THREE.MeshStandardMaterial({color:0x111820,metalness:.8,roughness:.25}),metal=new THREE.MeshStandardMaterial({color:0x718096,metalness:.85,roughness:.2}),green=new THREE.MeshStandardMaterial({color:0x43d17d,metalness:.2,roughness:.45});
function mesh(g,m){const x=new THREE.Mesh(g,m);x.castShadow=x.receiveShadow=true;return x}const cyl=(r,h,m=orange)=>mesh(new THREE.CylinderGeometry(r,r,h,40),m),box=(x,y,z,m=orange)=>mesh(new THREE.BoxGeometry(x,y,z),m);
const robot=new THREE.Group();scene.add(robot);const basePed=cyl(.75,.32,dark);basePed.position.y=.16;robot.add(basePed);const baseTop=cyl(.6,.22);baseTop.position.y=.43;robot.add(baseTop);const yaw=new THREE.Group();yaw.position.y=.54;robot.add(yaw);const shoulderHousing=cyl(.48,.72);shoulderHousing.rotation.z=Math.PI/2;shoulderHousing.position.y=.36;yaw.add(shoulderHousing);const shoulderPivot=new THREE.Group();shoulderPivot.position.y=.36;yaw.add(shoulderPivot);const L1=2.65,L2=2.25;const upper=box(.48,L1,.62);upper.position.y=L1/2;shoulderPivot.add(upper);const shoulderCap=cyl(.39,.68,dark);shoulderCap.rotation.z=Math.PI/2;shoulderPivot.add(shoulderCap);const elbowPivot=new THREE.Group();elbowPivot.position.y=L1;shoulderPivot.add(elbowPivot);const elbowCap=cyl(.36,.7,dark);elbowCap.rotation.z=Math.PI/2;elbowPivot.add(elbowCap);const fore=box(.42,L2,.55);fore.position.y=L2/2;elbowPivot.add(fore);const wrist=new THREE.Group();wrist.position.y=L2;elbowPivot.add(wrist);const wristBody=cyl(.3,.65);wristBody.rotation.z=Math.PI/2;wrist.add(wristBody);const palm=box(.7,.42,.45,dark);palm.position.y=.42;wrist.add(palm);const leftFinger=box(.16,.8,.18,metal),rightFinger=box(.16,.8,.18,metal);leftFinger.position.y=rightFinger.position.y=1;wrist.add(leftFinger,rightFinger);const tip=new THREE.Object3D();tip.position.y=1.45;wrist.add(tip);
const object=box(.55,.55,.55,orange);object.position.set(-2.35,.28,0);scene.add(object);const targetPad=cyl(.65,.08,green);targetPad.position.set(2.1,.04,1.4);scene.add(targetPad);
function resize(){const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(host);resize();
function status(t,c='ok'){$('statusText').textContent=t;$('statusText').className=c}function setMode(m){mode=m;$('modeText').textContent=m;status('READY')}
function update(record=true){const b=THREE.MathUtils.degToRad(+base.value),s=THREE.MathUtils.degToRad(+shoulder.value-90),e=THREE.MathUtils.degToRad(+elbow.value);yaw.rotation.y=b;shoulderPivot.rotation.z=-s;elbowPivot.rotation.z=-e;const gap=.18+(+grip.value/100)*.34;leftFinger.position.x=-gap;rightFinger.position.x=gap;leftFinger.rotation.z=-.12;rightFinger.rotation.z=.12;$('baseVal').textContent=base.value+'°';$('shoulderVal').textContent=shoulder.value+'°';$('elbowVal').textContent=elbow.value+'°';$('gripVal').textContent=grip.value+'%';$('speedVal').textContent=speed.value+'%';scene.updateMatrixWorld(true);const p=new THREE.Vector3();tip.getWorldPosition(p);$('xPos').textContent=(p.x*100).toFixed(1)+' mm';$('yPos').textContent=(p.y*100).toFixed(1)+' mm';$('zPos').textContent=(p.z*100).toFixed(1)+' mm';$('reach').textContent=(Math.hypot(p.x,p.y-.9,p.z)*100).toFixed(1)+' mm';const d=p.distanceTo(object.position);$('sensorText').textContent=d<1.0?'OBJECT DETECTED':'NO OBJECT';if(held){object.position.copy(p);object.position.y-=.28}if(record){telemetry.push([p.x*100,p.y*100,p.z*100]);if(telemetry.length>80)telemetry.shift();drawChart()}return p}
function drawChart(){const c=$('chart'),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#20334c';ctx.lineWidth=1;for(let y=35;y<h;y+=35){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}const cols=['#ff5b67','#43d17d','#55d9ff'];for(let k=0;k<3;k++){ctx.strokeStyle=cols[k];ctx.lineWidth=2;ctx.beginPath();telemetry.forEach((p,i)=>{const x=i/(Math.max(79,telemetry.length-1))*w,y=h/2-p[k]*.16;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}}
function assertMove(){return !estopped}async function moveTo(p){if(!assertMove())return false;running=true;status('MOVING','warn');const from={b:+base.value,s:+shoulder.value,e:+elbow.value,g:+grip.value};const duration=350+1300*(1-(+speed.value/100)),steps=Math.max(12,Math.round(duration/25));for(let i=1;i<=steps;i++){if(estopped){running=false;return false}const t=i/steps,u=t*t*(3-2*t);base.value=from.b+(p.b-from.b)*u;shoulder.value=from.s+(p.s-from.s)*u;elbow.value=from.e+(p.e-from.e)*u;grip.value=from.g+(p.g-from.g)*u;update(i%3===0);await sleep(duration/steps)}running=false;status('READY');return true}
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));function solveIK(xmm,ymm,zmm){const x=xmm/100,y=ymm/100,z=zmm/100,H=.90,A=L1,B=L2+1.45;const radial=Math.hypot(x,z),dy=y-H,d=Math.hypot(radial,dy);if(d>A+B||d<Math.abs(A-B))return null;const cosE=clamp((d*d-A*A-B*B)/(2*A*B),-1,1),q2=Math.acos(cosE);const phi=Math.atan2(dy,radial),q1=phi-Math.atan2(B*Math.sin(q2),A+B*Math.cos(q2));let s=THREE.MathUtils.radToDeg(Math.PI/2-q1),e=-THREE.MathUtils.radToDeg(q2);let b=THREE.MathUtils.radToDeg(Math.atan2(z,-x));s=clamp(s,10,150);e=clamp(e,-120,120);b=clamp(b,-180,180);return{b,s,e,g:+grip.value}}
[base,shoulder,elbow,grip,speed].forEach(x=>x.addEventListener('input',()=>{if(!estopped&&mode==='MANUAL')update()}));$('open').onclick=()=>{if(!estopped){grip.value=100;update()}};$('close').onclick=()=>{if(!estopped){grip.value=0;update()}};$('modeBtn').onclick=()=>{if(!running&&!estopped)setMode(mode==='MANUAL'?'AUTO':'MANUAL')};$('home').onclick=()=>moveTo({b:0,s:55,e:55,g:40});
$('teach').onclick=()=>{if(estopped)return;saved.push({b:+base.value,s:+shoulder.value,e:+elbow.value,g:+grip.value});renderSaved()};function renderSaved(){const el=$('savedPositions');if(!saved.length){el.innerHTML='<p class="muted">Još nema spremljenih položaja.</p>';return}el.innerHTML='';saved.forEach((p,i)=>{const r=document.createElement('div');r.className='saved-row';r.innerHTML=`<span>P${i+1}: B ${p.b.toFixed(0)}° • R ${p.s.toFixed(0)}° • L ${p.e.toFixed(0)}°</span><button>Idi</button><button class="secondary">×</button>`;r.children[1].onclick=()=>moveTo(p);r.children[2].onclick=()=>{saved.splice(i,1);renderSaved()};el.appendChild(r)})}$('clearTeach').onclick=()=>{saved=[];renderSaved()};
$('goXYZ').onclick=async()=>{if(estopped)return;const p=solveIK(+$('targetX').value,+$('targetY').value,+$('targetZ').value);if(!p){$('ikInfo').textContent='⚠️ Cilj je izvan radnog prostora robota.';return}$('ikInfo').textContent=`IK: baza ${p.b.toFixed(1)}°, rame ${p.s.toFixed(1)}°, lakat ${p.e.toFixed(1)}°`;await moveTo(p)};
$('runSequence').onclick=async()=>{if(estopped||running||!saved.length)return;setMode('AUTO');for(const p of saved){if(!(await moveTo(p)))break}if(!estopped)status('PROGRAM DONE')};
$('demo').onclick=async()=>{if(estopped||running)return;setMode('AUTO');const seq=[{b:-55,s:55,e:45,g:80},{b:35,s:90,e:-35,g:35},{b:70,s:65,e:35,g:80},{b:0,s:55,e:55,g:40}];for(const p of seq){if(!(await moveTo(p)))break}if(!estopped)status('DEMO DONE')};
$('pickPlace').onclick=async()=>{if(estopped||running)return;setMode('AUTO');const pick=[{b:0,s:70,e:35,g:100},{b:0,s:118,e:-70,g:100},{b:0,s:118,e:-70,g:0}],place=[{b:-145,s:70,e:25,g:0},{b:-145,s:112,e:-65,g:0},{b:-145,s:112,e:-65,g:100}];for(const p of pick){if(!(await moveTo(p)))return}held=true;status('GRIPPING','warn');await sleep(300);for(const p of place){if(!(await moveTo(p)))return}held=false;object.position.set(2.1,.32,1.4);cycles++;$('cycles').textContent=cycles;status('CYCLE DONE')};
$('estop').onclick=()=>{estopped=!estopped;if(estopped){running=false;status('STOPPED','stop');$('estop').textContent='↻ RESET E‑STOP'}else{$('estop').textContent='🛑 EMERGENCY STOP';status('READY');setMode('MANUAL')}};
function animate(){requestAnimationFrame(animate);orbit.update();renderer.render(scene,camera)}update();animate();
